//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: cryptim.java
//
//  Created by hafidzi on 4/3/14.
//

#ifndef _cryptim_H_
#define _cryptim_H_

@class IOSIntArray;
@class IOSObjectArray;

#import "JreEmulation.h"

@interface cryptim : NSObject {
 @public
  NSString *outputFile_;
  int tabFlag_;
  IOSObjectArray *S_box_;
  IOSObjectArray *S_box_inverse_;
  IOSIntArray *key_;
  IOSObjectArray *State_;
  IOSObjectArray *sliceState_;
  IOSIntArray *extend_key_;
  IOSIntArray *Rcon_;
}

+ (NSString *)tempKeyD;
+ (void)setTempKeyD:(NSString *)tempKeyD;
+ (NSString *)tempCodeD;
+ (void)setTempCodeD:(NSString *)tempCodeD;
+ (NSString *)outputc;
+ (void)setOutputc:(NSString *)outputc;
+ (NSString *)outputh;
+ (void)setOutputh:(NSString *)outputh;
+ (NSString *)inEnTextArea;
+ (void)setInEnTextArea:(NSString *)inEnTextArea;
+ (NSString *)inTempTextArea;
+ (void)setInTempTextArea:(NSString *)inTempTextArea;
+ (NSString *)inDeTextArea;
+ (void)setInDeTextArea:(NSString *)inDeTextArea;
+ (NSString *)fKTextArea;
+ (void)setFKTextArea:(NSString *)fKTextArea;
+ (NSString *)fPTextArea;
+ (void)setFPTextArea:(NSString *)fPTextArea;
+ (NSString *)fBrowseTextField;
+ (void)setFBrowseTextField:(NSString *)fBrowseTextField;
+ (void)mainWithNSStringArray:(IOSObjectArray *)args;
- (void)RotWordWithIntArray:(IOSIntArray *)temp;
- (int)SubWordWithInt:(int)a;
- (int)SubWord_inverseWithInt:(int)a;
- (NSString *)hexFormatWithInt:(int)integer;
- (void)keyGeneration;
- (void)msgEncrypt;
- (void)roundLoopWithInt:(int)time;
- (void)MixColumn;
- (int)MultiWithInt:(int)a
            withInt:(int)b;
- (void)msgDecrypt;
- (void)roundLoop_inverseWithInt:(int)time;
- (void)MixColumn_inverse;
- (void)getSliceWithIntArray:(IOSIntArray *)codeNum;
- (void)getSlicetoCubeXWithInt:(int)slice
                  withIntArray:(IOSIntArray *)codeNum;
- (void)getSlicetoCubeYWithInt:(int)slice
                  withIntArray:(IOSIntArray *)codeNum;
- (void)getSlicetoCubeZWithInt:(int)slice
                  withIntArray:(IOSIntArray *)codeNum;
- (void)getRotateSliceWithInt:(int)axis;
- (void)outSliceWithIntArray:(IOSIntArray *)codeNum;
- (void)outRotateSliceWithInt:(int)slice
                 withIntArray:(IOSIntArray *)codeNum;
- (void)outSlicetoCubeWithInt:(int)slice
                 withIntArray:(IOSIntArray *)codeNum;
- (void)getKeyWithIntArray:(IOSIntArray *)keyNum;
- (void)inEnX;
- (void)inDeX;
- (void)inEnY;
- (void)inDeY;
- (void)inEnZ;
- (void)inDeZ;
- (void)inEnData;
- (void)outEnData;
- (void)inDeData;
- (void)outDeData;
- (void)fEnData;
- (void)fDeData;
- (void)displayProgressWithInt:(int)pL;
- (NSString *)convertHexToStringWithNSString:(NSString *)hex;
- (void)inStartButtonActionPerformed;
- (void)fBrowseButtonActionPerformed;
- (id)init;
- (void)copyAllFieldsTo:(cryptim *)other;
@end

J2OBJC_FIELD_SETTER(cryptim, outputFile_, NSString *)
J2OBJC_FIELD_SETTER(cryptim, S_box_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(cryptim, S_box_inverse_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(cryptim, key_, IOSIntArray *)
J2OBJC_FIELD_SETTER(cryptim, State_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(cryptim, sliceState_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(cryptim, extend_key_, IOSIntArray *)
J2OBJC_FIELD_SETTER(cryptim, Rcon_, IOSIntArray *)

#endif // _cryptim_H_
